### ISSUE TITLE
Python wrapper, pip install

### ISSUE THREAD

**Issue by neubig** [chikiulo/yisi#1]
Hello!

We'd be interested in using YiSi (for example in our analysis toolkit [compare-mt](https://github.com/neulab/compare-mt)), and it'd be very convenient to do so if there was a way to access it through Python. It'd be particularly nice if this could be done by installing through pip. I know this might be a little bit of work, but I just thought I'd make the request in case.

**Comment by chikiulo** [comment]
It is top in our todo list. It should be available in this summer.

**Comment by shaikr** [comment]
Hi, bumping up this issue - is it still in progress?
I'm having lots of problems with the installation process :(

**Comment by kocmitom** [comment]
I was also unable to go through the installation process. Would it be possible to revise the instructions or is the python wrapper still planned?
